import 'dotenv/config';

const NODE_ENV = process.env.NODE_ENV || "development";
const PORT = process.env.PORT || 8000;
const BROWSERLESS_TOKEN = process.env.BROWSERLESS_TOKEN;
const TOKEN_SECRET = process.env.TOKEN_SECRET;
const MONGODB_URI = process.env.MONGODB_URI;
const CLIENT_URL = process.env.CLIENT_URL;
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;
const ADMIN_NAME = process.env.ADMIN_NAME;
const ADMIN_EMAIL = process.env.ADMIN_EMAIL;
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD;

export {
  PORT,
  NODE_ENV,
  BROWSERLESS_TOKEN,
  TOKEN_SECRET,
  MONGODB_URI,
  CLIENT_URL,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  ADMIN_NAME,
  ADMIN_EMAIL,
  ADMIN_PASSWORD,
};